=== Draion/Gamekit/Samples/LuaEditor/Config/config.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:attribute name="name"  type="xs:string"/>
  <xs:attribute name="value" type="xs:string"/>

  <xs:element name="config">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="section"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>

  <xs:element name="section">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="group" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute ref="name" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="group">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="entry"  minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute ref="name" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="entry">
    <xs:complexType>
    <xs:attribute ref="name" use="required"/>
    <xs:attribute ref="value"/>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== Draion/Gamekit/Samples/LuaEditor/Config/luconfig.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="config.xsl"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="config.xsd">

  <section name="app">
    <group name="runtime">
      <entry name="win32_path" value="../LuaRuntime/RelWithDebInfo/AppLuaRuntime.exe"/>
      <entry name="linux_path" value="../LuaRuntime/RelWithDebInfo/AppLuaRuntime"/>
    </group>
    <group name="debug_runtime">
      <entry name="win32_path" value="../LuaRuntime/Debug/AppLuaRuntime.exe"/>
      <entry name="linux_path" value="../LuaRuntime/Debug/AppLuaRuntime"/>
    </group>
    <group name="help">
      <entry name="path" value="Help/OgreKitLuaApi.chm"/>
      <entry name="topic" value="Help/index.hhk"/>
    </group>
    <group name="edit">
      <entry name="tab_size" value="4"/>
      <entry name="indent_size" value="4"/>
      <entry name="set_tab_indent" value="true"/>
      <entry name="font_name" value="Verdana"/>
      <entry name="font_size" value="11"/>
      <entry name="linenumber_margin" value="40"/>
      <entry name="bookmark_margin" value="16"/>
      <entry name="folder_margin" value="16"/>
      <entry name="keywords" value="and break do else elseif end false for function if in local nil not or repeat return then true until while "/>      
    </group>
    <group name="edit_font_color">
      <entry name="default" value="0 0 0"/>
      <entry name="comment" value="0 128 0"/>
      <entry name="comment_line" value="0 128 0"/>
      <entry name="comment_doc" value="0 128 0"/>
      <entry name="number" value="0 128 128"/>
      <entry name="word" value="0 0 128"/>
      <entry name="string" value="128 0 128"/>
      <entry name="identifier" value="0 0 0"/>
      <entry name="preprocessor" value="128 0 0"/>
      <entry name="operator" value="128 128 0"/>
    </group>
    <group name="edit_font_bold">
      <entry name="word" value="true"/>
    </group>
    <group name="edit_font_bgcolor">
      <entry name="default" value="255 255 255"/>
    </group>
    <group name="edit_view">
      <entry name="eol" value="false"/>
      <entry name="white_space" value="false"/>
      <entry name="indent_guide" value="false"/>      
      <entry name="long_line_mark" value="false"/>
      <entry name="line_number" value="true"/>
      <entry name="folder" value="true"/>
      <entry name="bookmark" value="true"/>
    </group>
    <group name="file">
      <entry name="base_blend" value="Data/base.blend"/>
      <entry name="proj_template" value="Config/lutemplate.xml"/>
    </group>
  </section>

</config>
